In [27]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols


df = pd.DataFrame(pd.read_csv('../Dataset/PanicSymptoms.csv'))

df

   Subject  Cog4  Cog8  Cog12  Beh4  Beh8  Beh12  CogBeh4  CogBeh8  CogBeh12
0      1.0    60    66     60    66    56     59       45       47        45
1      2.0    60    65     67    68    67     60       45       46        45
2      3.0    68    62     61    67    65     65       46       45        45
3      4.0    67    58     66    69    70     62       42       45        42
4      5.0    68    50     64    68    62     57       41       41        42
5      6.0    67    59     61    60    57     58       46       42        43
6      7.0    67    56     65    66    60     57       45       43        44
7      8.0    70    60     68    68    71     66       45       40        45
8      9.0    60    70     65    62    65     61       46       43        43
9     10.0    61    61     67    66    60     61       44       46        43

In [28]:
df1 = pd.DataFrame({'Cog': np.repeat([['Cog']], 30),
                   'Dosage': np.repeat([4, 8, 12], 10),
                   'Symptoms':[60, 60, 68, 67, 68, 67, 67, 70, 60, 61,
                               66, 65, 62, 58, 50, 59, 56, 60, 70, 61,
                               60, 67, 61, 66, 64, 61, 65, 68, 65, 67]})

df2 = pd.DataFrame({'Beh': np.repeat([['Beh']], 30),
                   'Dosage': np.repeat([4, 8, 12], 10),
                   'Symptoms':[66, 68, 67, 69, 68, 60, 66, 68, 62, 66,
                               56, 67, 65, 70, 62, 57, 60, 71, 65, 60,
                               59, 60, 65, 62, 57, 58, 57, 66, 61, 61]})

df3 = pd.DataFrame({'CogBeh': np.repeat([['CogBeh']], 30),
                   'Dosage': np.repeat([4, 8, 12], 10),
                   'Symptoms':[45, 45, 46, 42, 41, 46, 45, 45, 46, 44,
                               47, 46, 45, 45, 41, 42, 43, 40, 43, 46,
                               45, 45, 45, 42, 42, 43, 44, 45, 43, 43]})
df1

    Cog  Dosage  Symptoms
0   Cog       4        60
1   Cog       4        60
2   Cog       4        68
3   Cog       4        67
4   Cog       4        68
5   Cog       4        67
6   Cog       4        67
7   Cog       4        70
8   Cog       4        60
9   Cog       4        61
10  Cog       8        66
11  Cog       8        65
12  Cog       8        62
13  Cog       8        58
14  Cog       8        50
15  Cog       8        59
16  Cog       8        56
17  Cog       8        60
18  Cog       8        70
19  Cog       8        61
20  Cog      12        60
21  Cog      12        67
22  Cog      12        61
23  Cog      12        66
24  Cog      12        64
25  Cog      12        61
26  Cog      12        65
27  Cog      12        68
28  Cog      12        65
29  Cog      12        67

In [29]:
model = ols('Symptoms ~ C(Cog) + C(Dosage) + C(Cog):C(Dosage)', data=df1).fit()
sm.stats.anova_lm(model, typ=1)

                    df  sum_sq    mean_sq         F    PR(>F)
C(Cog)             0.0     0.0        NaN       NaN       NaN
C(Dosage)          2.0   102.2  51.100000  2.758848  0.081244
C(Cog):C(Dosage)   0.0     0.0        NaN       NaN       NaN
Residual          27.0   500.1  18.522222       NaN       NaN

In [30]:
model = ols('Symptoms ~ C(Beh) + C(Dosage) + C(Beh):C(Dosage)', data=df2).fit()
sm.stats.anova_lm(model, typ=1)

                    df  sum_sq    mean_sq         F    PR(>F)
C(Beh)             0.0     0.0        NaN       NaN       NaN
C(Dosage)          2.0   145.8  72.900000  4.914607  0.015129
C(Beh):C(Dosage)   0.0     0.0        NaN       NaN       NaN
Residual          27.0   400.5  14.833333       NaN       NaN

P < 0.5 so in Behavioral method we can acknowledge that drug dosage have significant impact on the outcome.

In [31]:
model = ols('Symptoms ~ C(CogBeh) + C(Dosage) + C(CogBeh):C(Dosage)', data=df3).fit()
sm.stats.anova_lm(model, typ=1)

                       df  sum_sq   mean_sq         F    PR(>F)
C(CogBeh)             0.0     0.0       NaN       NaN       NaN
C(Dosage)             2.0     3.8  1.900000  0.568736  0.572878
C(CogBeh):C(Dosage)   0.0     0.0       NaN       NaN       NaN
Residual             27.0    90.2  3.340741       NaN       NaN